### ISSUE TITLE
Allow passing of a function([function])

### ISSUE THREAD

**Issue by whitfin** [vvo/chainit#6]
https://github.com/vvo/chainit/blob/master/index.js#L99 shows that if the last argument is a function, we treat that as the callback.

However, consider this scenario:

```
// We have a callback added onto the function
chainit.add([object], name, function(string){

});

// function is treated as the final callback
chainit.add([object], name, function(string, function){

});
```

If I were to pass a string, the callback would be implemented for me:

```
chainit.add([object], name, function(string){

});

// the function gets called
function(string, cb){

});
```

but because I pass a function, this happens

```
chainit.add([object], name, function(function){

});

// the function gets called
function(cb){

});
```

This leads to confusion and means that sometimes it will be necessary to pass an empty function if you don't require a callback.

It would be better if it operated the same way the entire time.

**EDIT**: it could be fixed by just passing a boolean param to `add()` if we want to use our function as the cb, or the generated one.

Here is perhaps a better example:

```
chainit.add([object], 'myFunction', function(param1, callback){
    console.log(param1);
    callback();
})

// Logs out the string, callback is defined
[object].myFunction(string);

// Logs out the function, callback is undefined
[object].myFunction(otherFunction);

```

**Comment by vvo** [comment]
@iwhitfield Unfortunately there is no clean way to do what you want to do: mixing synchronous and asynchronous API.

Either you have a full asynchronous API or a full synchronous API.

See https://github.com/vvo/chainit#mixing-asyncsync-apis

Did I get your problem right?

**Comment by whitfin** [comment]
@vvo I think there is some confusion. The issue I'm referring to is that if I create a chained function which has two parameters (param1, param2), with param2 being a callback, it seems that I can call this like this:

```
func(variable, callback) 
```

or

```
func(variable)
```

In both cases, it appears that param2 is still accessible (even when it isn't passed). This is therefore the expected behaviour.

However, if my passed parameter is a function:

```
func(someFunction)
```

the param2 callback will no longer exist, meaning if it's used in the function, it will be undefined. It is strictly related to the fact I pass a function as the last variable. It seems that if I pass any other object type as the last variable, a callback parameter is added (which I like).

Does this make sense? I'm not relating this to the execution, just the passed in parameters.

**Comment by vvo** [comment]
Oh yes, I stumble on this problem a while ago.

For example, using webdriverjs, you can't do `.execute(function(){})` without the args value, that is sad.

But the problem is that we can't now in advance that the definition of `execute` takes a function as first parameter because there are no types in JavaScript.

Thus how do we know that the first passed function has to be used as an argument to the `execute` method rather as a callback?

As you can see in the webdriverjs documentation, this is indeed written: https://github.com/camme/webdriverjs

> execute(String or Function script, Array arguments, Function callback)
> Inject a snippet of JavaScript into the page for execution in the context of the currently selected frame. If > script is a Function, arguments is required.

If you find a good solution to this I will be happy to use it. Write a unit test and try to fix it.

**Comment by psirenny** [comment]
I'm having the same issue. I think the cleanest solution is that the the passed in parameter is simply not treated as the callback. It will add more code of course, but nothing too ugly.

i.e.:

```
SomeObj.prototype.method = function (val, cb, next) {
  handle(val, function (err) {
    cb(err);
    next(); // go to the next chained method
  });
}
```

I happen to think the above solution is easier to understand as well. It's not as elegant as writing this though:

```
SomeObj.prototype.method = function (val, cb)  {
  handle(val, cb);
}
```

What do you think?

**Comment by whitfin** [comment]
@psirenny That's the behaviour I would desire, it removes the ambiguity. Otherwise, you'd have to check for `undefined` or pass an empty function if you didn't want to execute anything as a callback.

**Comment by christian-bromann** [comment]
I just found a nifty workaround for that. The following example takes a function as last parameter and chainit will not execute it as callback:

``` js
obj.prototype.functionThatTakesAFuncAsLastParam = function(param1,func) {
    chainit.add(obj, '__tmp__', function(cb) {
         // do something
         // ...
         // call synchronous function
         func();
    });

    obj.__tmp__();
    obj.__tmp__ = undefined;
}
```

I know that is pretty hacky but the only way I think to create functions that dont care about any callback and take a function as last parameter to do some kind of synchronous stuff.
